server:
  port: 9001
spring:
  application:
    name: livegoods-recommendation
  profiles:
    active: mongo,commons
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.126:8761/eureka/
  instance:
    prefer-ip-address: true